.gitignore, .npmrc, api-extractor.json, package-lock.json, package.json, tsconfig.json, vite.config.ts
This PR sets up all the configs we need to run & build the module.
=> Setup moduleconfigs

lib/control_panel/tab_panels/data.ts, lib/headless/parahelper.ts, lib/parachart/parachart.ts, lib/paraview/paraview.ts, lib/view_temp/axisline.ts, lib/view_temp/bar.ts, lib/view_temp/base_view.ts, lib/view_temp/datalayer.ts, lib/view_temp/label.ts, lib/view_temp/pointchart.ts, lib/view_temp/ticklabeltier.ts, lib/view_temp/xychart.ts
=> Start on Inclusio integration.

lib/common/vector.ts, lib/store/parastore.ts, lib/view/bar.ts, lib/view/base_view.ts, lib/view/chart_type/radialchart.ts, lib/view/data/datapoint.ts, lib/view/data/series.ts, lib/view/datalayer.ts, lib/view/highlights_layer.ts, lib/view/label.ts, lib/view/line.ts, lib/view/selectionlayer.ts, lib/view/shape/path.ts, lib/view/shape/sector.ts, lib/view/xychart.ts
=> Re-add selection.

lib/audio/sonifier.ts, lib/components/aria_live/aria_live.ts, lib/components/aria_live/voicing.ts, lib/control_panel/control_panel.ts, lib/control_panel/tab_panels/controls.ts, lib/control_panel/tab_panels/description.ts, lib/parachart/parachart.ts, lib/paraview/paraview.ts, lib/store/keymap.ts, lib/store/keymap_manager.ts, lib/store/parastore.ts, lib/view/bar.ts, lib/view/base_view.ts, lib/view/data/datapoint.ts, lib/view/datalayer.ts, lib/view/xychart.ts, src/stories/ffb-page-11.json, src/stories/ffb-page-12.json, src/stories/ffb-page-14.json, src/stories/ffb-page-15-1.json, src/stories/ffb-page-15-2.json, src/stories/ffb-page-4-1.json, src/stories/ffb-page-4-2.json, src/stories/ffb-page-6-1.json, src/stories/ffb-page-6-2.json
=> Add more FFB fixes.

package-lock.json, package.json
Adds Pie Chart Summaries by bumping ParaSummary dependence
=> Add Pie Chart Summaries

package-lock.json, package.json
=> Improve summary

lib/paraview/paraview.ts, lib/view/base_view.ts, lib/view/data/data.ts, lib/view/data/datapoint.ts, lib/view/xychart.ts
=> Remove play note on chart focus.

etc/paracharts.api.md, lib/view/data/datapoint.ts, lib/view/xychart.ts, package-lock.json, package.json
Adds series labels to datapoint and overall series in multiseries summaries.
=> Added series labels

lib/store/settings_defaults.ts, lib/view/bar.ts
=> Fix stacked bar chart drawing.

headless_live.html, tsconfig.json, vite.config.ts
=> Add headless live server demo.

etc/paracharts.api.md, lib/control_panel/tab_panels/description.ts, lib/paraview/paraview.ts, lib/store/parastore.ts
=> Set description caption after summarizer is created.

lib/control_panel/control_panel.ts, lib/store/settings_defaults.ts, lib/view/data/chart_landing.ts, package-lock.json, package.json
=> Remove initial cpanel focus.

lib/control_panel/control_panel.ts, lib/env.d.ts, lib/store/keymap.ts, lib/view/datalayer.ts, vite.config.ts
To announce them: `Ctrl+Shift+V`
Closes #153.
=> Embed version number and hash.

lib/control_panel/datatable.ts, lib/control_panel/tab_panels/data.ts, lib/store/parastore.ts, src/stories/Chart.ts
=> Import datatable from Todo.

lib/control_panel/tab_panels/data.ts, lib/store/parastore.ts
=> Re-add save data button.

lib/paraview/controller.ts
=> Fix shifted hotkeys.

etc/paracharts.api.md, lib/control_panel/tab_panels/data.ts, lib/paraview/paraview.ts, lib/store/parastore.ts, lib/view/data/datapoint.ts, lib/view/data/series.ts, lib/view/layers/data/chart_type/bar_chart.ts, lib/view/layers/data/chart_type/heatmap.ts, lib/view/layers/data/chart_type/histogram.ts, lib/view/layers/data/chart_type/point_chart.ts, lib/view/layers/data/chart_type/radial_chart.ts, lib/view/layers/data/chart_type/xy_chart.ts
=> Re-add JIM to SVG (and fix dialog).

lib/store/settings_defaults.ts, lib/store/settings_types.ts, lib/view/data/data.ts, lib/view/data/datapoint.ts, lib/view/data/series.ts, lib/view/layers/annotation/annotation_layer.ts, lib/view/layers/data/chart_type/line_chart.ts, lib/view/layers/data/data_layer.ts, lib/view/layers/highlights_layer.ts, lib/view/shape/path.ts
Closes #204.
Closes #205.
Closes #206.
Closes #207.
=> Add misc fixes.

lib/view/document_view.ts
=> Prevent default legends on single-series charts.

lib/control_panel/tab_panels/controls.ts, lib/paraview/paraview.ts, lib/store/settings_defaults.ts, lib/store/settings_types.ts, lib/view/layers/data/data_layer.ts
=> Make exiting fullscreen exit LV mode.

lib/paraview/controller.ts, lib/store/keymap_manager.ts
=> Fix keyboard selection extension.

etc/paracharts.api.md, lib/common/axisinfo.ts, lib/control_panel/control_panel.ts, lib/control_panel/tab_panels/description.ts, lib/parachart/parachart.ts, lib/paraview/hotkey_actions.ts, lib/paraview/paraview.ts, lib/store/index.ts, lib/store/keymap.ts, lib/store/keymap_manager.ts, lib/store/parastore.ts, lib/view/axis.ts, lib/view/base_view.ts, lib/view/data/datapoint.ts, lib/view/document_view.ts, lib/view/layers/data/chart_type/heatmap.ts, lib/view/layers/data/chart_type/histogram.ts, lib/view/layers/data/chart_type/line_chart.ts, lib/view/layers/data/chart_type/point_chart.ts, lib/view/layers/data/chart_type/radial_chart.ts, lib/view/layers/data/chart_type/scatter_chart.ts, lib/view/layers/data/chart_type/xy_chart.ts, lib/view/layers/data/data_layer.ts
=> Fix dangling listeners + setting observers issue.

lib/common/axisinfo.ts, lib/common/vector.ts, lib/view/label.ts, lib/view/ticklabeltier.ts
=> Improve tick label alignment.

lib/store/settings_defaults.ts, lib/store/settings_types.ts, lib/view/layers/data/chart_type/bar_chart.ts, lib/view/legend.ts
=> Add min bar width setting.

src/stories/Chart.ts
=> Fix Storybook legend order.

lib/paraview/hotkey_actions.ts, lib/store/keymap.ts
=> Fix repeat hotkey.

package-lock.json, package.json
Updates ParaModel with updated axis handling & without axis defaults,
Updates chart-data without axes orientation for bar family manifests
=> Fixes for axes title orientation

lib/parachart/parachart.ts, lib/paraview/controller.ts, lib/paraview/paraview.ts, lib/store/settings_defaults.ts, lib/store/settings_types.ts
=> Add `isStatic` setting.

etc/paracharts.api.md, lib/api/api.ts, lib/control_panel/tab_panels/data.ts, lib/headless/parahelper.ts, lib/paraview/paraview.ts
=> Add support for downloading chart as a PNG.

lib/view/document_view.ts, lib/view/layers/data/chart_type/line_chart.ts
=> Fix line chart legend drawing.

etc/paracharts.api.md, lib/parachart/parachart.ts
=> Add data attribute.

src/stories/education.stories.ts
=> Added education stories

lib/view/layers/data/chart_type/line_chart.ts
=> Fixed symbols setting display

lib/control_panel/control_panel.ts
=> Allow setting cpanel icon.

lib/common/axisinfo.ts, lib/view/document_view.ts, lib/view/layers/data/chart_type/bar_chart.ts
=> Add provisional fix for swapped bar axis titles.

lib/control_panel/dialogs/soni_dialog.ts, lib/store/settings_defaults.ts, lib/store/settings_types.ts, lib/view/layers/data/chart_type/xy_chart.ts, lib/view/layers/data/data_layer.ts
=> Add chord arpeggio option.

lib/view/layers/data/chart_type/bar_chart.ts
=> Stack horiz bar stacks bottom-to-top.

etc/paracharts.api.md, lib/components/aria_live/aria_live.ts, lib/control_panel/tab_panels/description.ts, lib/parachart/parachart.ts, lib/paraview/hotkey_actions.ts
=> Put aria-live region back inside cpanel.

lib/paraview/paraview.ts, lib/store/settings_defaults.ts, lib/store/settings_types.ts, lib/view/axis/axis.ts, lib/view/axis/axis_line.ts, lib/view/axis/index.ts, lib/view/axis/rule.ts, lib/view/axis/tick_label_tier.ts, lib/view/axis/tick_strip.ts, lib/view/base_view.ts, lib/view/document_view.ts, lib/view/label.ts, lib/view/layout/flex.ts, lib/view/layout/grid.ts, lib/view/legend.ts
=> Add padded view anchors.

lib/paraview/paraview.ts
=> Remove width/height from exported SVG.

.storybook/preview.ts
Moves AI-enhanced charts above basic charts in Storybook. Closes #358
=> Move AI-enhanced charts above basic charts in Storybook

lib/view/axis/axis.ts, lib/view/axis/tick_label_tier.ts, lib/view/label.ts, lib/view/serieslabelstrip.ts
=> Fix ID issues.

lib/loader/paraloader.ts, lib/loader/slotloader.ts, lib/parachart/parachart.ts, src/demo/ai/ai_live.html
Adds description override to slot loader, similarly to how it was already added to ParaLoader.
Closes #424
=> Adds description override to slot loader

lib/paraview/hotkey_actions.ts, lib/store/parastore.ts, lib/view/base_view.ts, lib/view/layers/data/chart_type/line_chart.ts, lib/view/layers/data/data_layer.ts, lib/view/layers/data/navigation.ts
=> Improve extensive nav performance.

lib/audio/sonifier.ts, lib/store/settings_defaults.ts, lib/store/settings_types.ts, lib/view/layers/data/chart_type/calculator.ts, lib/view/layers/data/chart_type/xy_chart.ts
https://github.com/fizzstudio/Future-Work/issues/49
Adds continuous sonification for graphs by interpolating points between each rendered point and playing the sequence faster.
Also adds a system to remember if a series was focused before making changes that recreate the datapoints so that it may be instantly refocused after the new points are generated.
=> Sam graph improvements

lib/view/layers/data/chart_type/xy_chart.ts, lib/view/layers/data/data_layer.ts, lib/view/layers/data/navigation.ts
=> Adjust chord nav to old style.

lib/store/parastore.ts, lib/view/layers/data/chart_type/line_chart.ts, lib/view/layers/data/chart_type/scatter_chart.ts, lib/view/layers/data/data_layer.ts, lib/view/layers/data/navigation.ts
=> Add cluster landings

etc/paracharts.api.md, lib/view/data/datapoint.ts, lib/view/layers/data/chart_type/bar_chart.ts, lib/view/layers/data/chart_type/heatmap.ts, lib/view/layers/data/chart_type/line_chart.ts, lib/view/layers/data/chart_type/scatter_chart.ts, lib/view/shape/path.ts, lib/view/shape/rect.ts, lib/view/shape/sector.ts, lib/view/shape/shape.ts
=> Reduce clip path use.

etc/paracharts.api.md, lib/store/parastore.ts, lib/view/data/datapoint.ts, lib/view/layers/data/chart_type/heatmap.ts, lib/view/layers/data/chart_type/histogram.ts, lib/view/layers/data/chart_type/scatter_chart.ts, lib/view/layers/data/navigation.ts, lib/view/layers/highlights_layer.ts, lib/view/layers/selection_layer.ts
#453 
-Moves some functionality of checking if a datapoint is visited/selected from the store to the datapoint to improve performance
-DataCursors now store the DatapointView they are associated with, also to improve performance
=> Sam visit performance

lib/components/settings/slider.ts, lib/control_panel/tab_panels/chart.ts, lib/control_panel/tab_panels/colors.ts, lib/paraview/paraview.ts, lib/store/settings_defaults.ts, lib/store/settings_types.ts, lib/view/base_view.ts, lib/view/layers/data/chart_type/calculator.ts, lib/view/layers/data/chart_type/pie.ts, lib/view/layers/data/chart_type/radial_chart.ts, lib/view/layers/focus/focus_ring.ts, lib/view/shape/index.ts, lib/view/shape/sector.ts
=> Add radial slice explosion.

lib/control_panel/caption.ts, lib/control_panel/control_panel.ts, lib/control_panel/dialogs/advanced_controls_dialog.ts, lib/parachart/parachart.ts, lib/store/settings_defaults.ts, lib/store/settings_types.ts
=> Allow showing caption outside of cpanel.

lib/store/settings_defaults.ts, lib/view/layers/data/chart_type/heatmap.ts, lib/view/shape/rect.ts
-Heatmaps now display again
-Provisional `summary()` is used instead of `ParaSummary` to prevent errors
-`HeatmapTileView` now uses a child shape element, in line with other `DatapointView` classes
=> Fix heatmaps

package-lock.json, package.json
Removes intersection count and record count sentence from series summary.
See https://github.com/fizzstudio/ParaSummary/issues/36
=> Remove intersection count and record count sentences from series summary

lib/chart_types/base_chart.ts, lib/common/colors.ts, lib/parachart/parachart.ts, lib/paraview/paraview.ts, lib/store/parastore.ts, lib/view/data/datapoint.ts, lib/view/layers/annotation/annotation_layer.ts, lib/view/layers/data/navigation.ts, lib/view/layers/highlights_layer.ts, lib/view/shape/sector.ts
=> Add support for highlighting datapoints.

package-lock.json, package.json
=> Bump ui-components ver.

lib/paraview/paraview.ts, lib/store/settings_defaults.ts
=> Tweak horiz grid line visibility.
